### PR TITLE
fedora 38 has branched

### PR DESCRIPTION
**Pull request by jonathanspw**

### CODE REVIEW

**Comment by WerWolv** [comment]
Thank you!

Question though, I was searching around a bit and I fail to find any download links for any Fedora version except Fedora 37 and Rawhide. Does it really make sense to a) keep Fedora 36 and b) already add Fedora 38 since neither of them can be downloaded on any official page I could find. Am I just stupid?

**Comment by jonathanspw** [comment]
It is branched, but not released.  They branch and go through more testing/QA/work before release.

It's essentially a dev branch like rawhide, but it's the immediate dev prior to release as things start taking shape for the final release.

**Comment by WerWolv** [comment]
Okay. I'll keep this PR open for now and we can merge it once Fedora 38 is actually available for download

**Comment by jonathanspw** [comment]
I think it's time to merge this.  F38 beta ships March 14 :)

**Comment by iTrooz** [comment]
merged main into this, CI is now green, I think this is ready to merge

**Pull request merged**
