### PR TITLE
fix: use `find_library()` instead of `find_file()` to find system yara library

### PR DESCRIPTION
**Pull request by iTrooz**
Discord discussion: https://discord.com/channels/789833418631675954/789840633414025246/1213564050848485427

### CODE REVIEW

**Comment by iTrooz** [comment]
Fix https://github.com/WerWolv/ImHex/issues/1547

**Comment by iTrooz** [comment]
@kernaltrap8 Hey, could you try building/running ImHex using the code source of this PR please ?

**Comment by kernaltrap8** [comment]
> @kernaltrap8 Hey, could you try building/running ImHex using the code source of this PR please ?

sure, would there be any extra deps i'd need or just clone repo and run build commands?

**Comment by WerWolv** [comment]
No, same as before. It just looks for libyara in the correct place now

**Comment by kernaltrap8** [comment]
> No, same as before. It just looks for libyara in the correct place now

i cant get it to build...

```
:3 ~/g/ImHex[1]>cmake -B build -G "Ninja"                              \                                                              (yara|?) 14:41
                        -DCMAKE_BUILD_TYPE=Release                \
                        -DCMAKE_INSTALL_PREFIX="/usr"             \

-- Configuring ImHex v1.33.0
-- Enabled bundled plugin 'builtin'
-- Enabled bundled plugin 'decompress'
-- Enabled bundled plugin 'diffing'
-- Enabled bundled plugin 'disassembler'
-- Enabled bundled plugin 'fonts'
-- Enabled bundled plugin 'hashes'
-- Enabled bundled plugin 'script_loader'
-- Enabled bundled plugin 'ui'
-- Enabled bundled plugin 'visualizers'
-- Enabled bundled plugin 'windows'
-- Enabled bundled plugin 'yara_rules'
-- Version: 10.2.0
-- Build type: Release
nfd Platform: PLATFORM_LINUX
nfd Compiler: COMPILER_GNU
Using DBUS version: 1.15.8
-- Using the multi-header code from /home/aiden/git/ImHex/lib/third_party/nlohmann_json/include/
CMake Error at lib/external/pattern_language/CMakeLists.txt:53 (add_subdirectory):
  The source directory

    /home/aiden/git/ImHex/lib/external/pattern_language/external/libwolv

  does not contain a CMakeLists.txt file.


-- libpl static library is being created
CMake Error at lib/external/pattern_language/cli/CMakeLists.txt:25 (add_subdirectory):
  The source directory

    /home/aiden/git/ImHex/lib/external/pattern_language/external/cli11

  does not contain a CMakeLists.txt file.


-- Backtrace enabled! Header: execinfo.h
-- Found Zstd: /usr/lib64/libzstd.so
-- Enabling decompression support using ZSTD ()
-- Enabling decompression support using ZLIB (1.3.1)
-- Enabling decompression support using BZip2 ()
-- Could NOT find LibLZMA (missing: LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) (found version "5.6.0")
Setting warning flags
Enabling CAPSTONE_ARM_SUPPORT
Enabling CAPSTONE_ARM64_SUPPORT
Enabling CAPSTONE_M68K_SUPPORT
Enabling CAPSTONE_MIPS_SUPPORT
Enabling CAPSTONE_PPC_SUPPORT
Enabling CAPSTONE_SPARC_SUPPORT
Enabling CAPSTONE_SYSZ_SUPPORT
Enabling CAPSTONE_XCORE_SUPPORT
Enabling CAPSTONE_X86_SUPPORT
Enabling CAPSTONE_TMS320C64X_SUPPORT
Enabling CAPSTONE_M680X_SUPPORT
Enabling CAPSTONE_EVM_SUPPORT
Enabling CAPSTONE_MOS65XX_SUPPORT
Enabling CAPSTONE_WASM_SUPPORT
Enabling CAPSTONE_BPF_SUPPORT
Enabling CAPSTONE_RISCV_SUPPORT
Enabling CAPSTONE_SH_SUPPORT
Enabling CAPSTONE_TRICORE_SUPPORT
-- Found matching .NET runtime version '8.0.2' path='/opt/dotnet-sdk-bin-8.0/shared/'
-- Downloading ImHex-Patterns repo branch ImHex-v1.33.0...
-- Finished downloading ImHex-Patterns
-- Configuring incomplete, errors occurred!
:3 ~/g/ImHex[1]>
```

**Comment by iTrooz** [comment]
Did you clone/update submodules ?

`git submodule update --recursive --init`

**Comment by kernaltrap8** [comment]
> Did you clone/update submodules ?
> 
> `git submodule update --recursive --init`

let me try that again

**Comment by kernaltrap8** [comment]
compiling with this worked.

**Comment by iTrooz** [comment]
Awesome ! This is good to be merged then

**Pull request merged**
