### PR TITLE
ui: fixed theme not changing on startup

### PR DESCRIPTION
**Pull request by PredatorCZ**
As mentioned in comments in #447.

### CODE REVIEW

**Comment by birorobi** [comment]
Hello, it's not good, I'm grateful for your care and effort, but as soon as
I read the message on Gmail and switched to watching YouTube, in five
seconds everything collapsed and restarted..I give up buying a Laptop ...
L.p.


pet, 18. ožu 2022. u 12:56 Lukas Cone ***@***.***> napisao je:

**Comment by WerWolv** [comment]
Thank you!

**Comment by WerWolv** [comment]
@birorobi I don't think you're in the right place here. If you experienced any issues with ImHex, please open a new issue under the Issues tab here instead of commenting on random other issues / PRs

**Comment by birorobi** [comment]
..that we're obviously on the wrong wavelength..my fault, sorry

pet, 18. ožu 2022. u 17:03 WerWolv ***@***.***> napisao je:

**Comment by pauleric** [comment]
The default "hex.builtin.setting.interface.color" is 0, should lastTheme be initialized to -1?

**Pull request merged**
