### PR TITLE
New icons, as discussed in #545

### PR DESCRIPTION
**Pull request by zaafonin**
Not squashing commits yet, accepting suggestions on .png/.svg/.ico

### CODE REVIEW

**Comment by KillyMXI** [comment]
Honestly, added "bubble" gradient looks really old and cheap to me.

**Comment by zaafonin** [comment]
Tbh maybe. I'll try to add a more subtle effect then

**Comment by zaafonin** [comment]
Moving away from bubble gradients to a more "layered" look. Is this one better?

**Comment by WerWolv** [comment]
Why did you delete the MacOS icon? That one was awesome

**Comment by zaafonin** [comment]
Not deleted, just made the gloss less pronounced. It's still there
Icon1024

**Comment by zaafonin** [comment]
If removing shadows from the edges, 0 gets the "inside" shadow while 1 gets none. Which one looks better?

 imhex 1-2

imhex 1

**Comment by WerWolv** [comment]
The first one looks good. The previous one just had too much shadows I think. It looks kinda weird without any shadows too.

If you're happy with those too, I'm very much fine with the latest macOS icon and the first of those two icons you posted

**Comment by zaafonin** [comment]
Done from my side!

**Comment by WerWolv** [comment]
Thanks a lot for the contribution!

**Pull request merged**
