### PR TITLE
[EMSCRIPTEN] Add the ability to click web links

### PR DESCRIPTION
**Pull request by AnnsAnna**
This provides the ability to click on web links

### Screenshots
https://github.com/WerWolv/ImHex/assets/25822956/f418fa00-8bfb-4bcb-8c53-8a6d87457551

### CODE REVIEW

**Comment by iTrooz** [comment]
Hey, I have no idea why this worked, but normally you need to decode C strings passed to JavaScript. I fixed it: https://github.com/WerWolv/ImHex/commit/2186b56692c6df2232758c1dd8e9d9bae551e11d

**Comment by AnnsAnna** [comment]
I'd assume emscripten does it for you?, not too sure, I even had that at one point but it didn't change anything

**Comment by iTrooz** [comment]
> I'd assume emscripten does it for you?
I don't think so, as the emscripten docs says to use it: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html
> char * received from C/C++ can be converted to a JavaScript string using [UTF8ToString()](https://emscripten.org/docs/api_reference/preamble.js.html#UTF8ToString).

Plus, it wasn't working for me, it redirected me to URLs like `locahost:8080/129892180`

**Comment by AnnsAnna** [comment]
Do you use Firefox or Chromium? I'm now curious why this never happened to me

**Comment by iTrooz** [comment]
Firefox, and you ?

**Comment by AnnsAnna** [comment]
> Firefox, and you ?

Also Firefox

**Comment by iTrooz** [comment]
Well, I guess the reason why it worked will remain a mystery

**Pull request merged**
