### PR TITLE
Release CI

### LINKED ISSUE #504: request: create source tarballs with submodules included for releases
As a downstream distro packager, it would be really handy if releases had a tarball that included all the submodules as they're pinned in the repo at release time

### PR DESCRIPTION
**Pull request by iTrooz**
Fixes #504

### CODE REVIEW

**Comment by WerWolv** [comment]
Thanks a lot!
Would it be possible to do the same thing with the current artifacts as well? That would immensely simplify the whole release creation process

I found this action here that can maybe help: https://github.com/actions/download-artifact

**Comment by iTrooz** [comment]
(I'm going to push some commits to test this, sorry if it causes emails, I'm not sure how else to test the CI)

**Comment by iTrooz** [comment]
Everything should be good !

**Comment by iTrooz** [comment]
Btw, something I forgot to mention, you can simply disable the release workflow, and it will stop uploading artifacts to releases

**Comment by WerWolv** [comment]
Thanks a lot!

**Comment by classabbyamp** [comment]
Thanks for this! One thing I've noticed is that the `.git` directory is in the full sources tarball. it's 36 MB and doesn't need to be there (at least for most distro packaging)

**Comment by iTrooz** [comment]
Oooops. #569

**Pull request merged**
