### PR TITLE
open .hexproj files as a Project

### PR DESCRIPTION
**Pull request by iTrooz**

### CODE REVIEW

**Comment by iTrooz** [comment]
Fixes https://github.com/WerWolv/ImHex/issues/1057

**Comment by iTrooz** [comment]
By the way, I am really unsure about my implementation, especially `reinterpret_cast`. This PR as it is is more for me to get feedback, because I doubt the implementation is good

**Comment by WerWolv** [comment]
A regular `static_cast` should be enough here because we're just down-casting through a inheritance hierarchy. If you want to be extra careful you can use a `dynamic_cast` and then check if the result is not `nullptr` but that's probably not necessary

**Comment by iTrooz** [comment]
Done ! I went with `static_cast`

**Pull request merged**
