### PR TITLE
Appimage builder

### PR DESCRIPTION
**Pull request by wardwouts**
This creates a setup to fulfill https://github.com/WerWolv/ImHex/issues/81

I've successfully created AppImages for both v1.11.1 and the master branch using this.

### CODE REVIEW

**Comment by WerWolv** [comment]
Wow thanks a lot! I've been meaning to do this for ages!

Could this somehow be integrated into the existing github actions build process so new commits are automatically bundled? That would make distributing future releases as AppImages a lot easier for me as well

**Comment by wardwouts** [comment]
> Wow thanks a lot! I've been meaning to do this for ages!
> 
> Could this somehow be integrated into the existing github actions build process so new commits are automatically bundled? That would make distributing future releases as AppImages a lot easier for me as well

I don't know anything about github actions. But if creating and using docker containers there is possible, then running the following:
```
cd docker
export TAG=v1.2.3
build.sh
extract.sh
```
should put a tagged AppImage like `ImHex-v1.2.3-x86_64.AppImage` in that docker directory. It could be that the security options in `build.sh` need a little tweaking for github actions though. I've tried to keep the scripts straightforward, so they should be easy to adapt.

**Comment by WerWolv** [comment]
Hm it's probably best to separate it. ImHex is already built twice on Linux, once for the portable version and once for the flatpak because I don't think it lets you use a pre-built binary. In the docker image ImHex would then be compiled _again_ to package it into an AppImage.

This is out of scope of this PR so I'd merge this and later on try to integrate it into the github actions without docker.

Could you perhaps move everything you put into the `docker` folder into `/dist/AppImage` or something compareable? Since the `/dist` folder is where everything else related to building ImHex resides in

**Comment by wardwouts** [comment]
Done.

For github actions this is likely a showstopper: https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#supported-linux-capabilities
FUSE, which is needed to build the AppImage, really needs those additional capabilities.

**Comment by WerWolv** [comment]
Thanks :)

The AppImage documentation seems to suggest using this action here: https://github.com/marketplace/actions/build-appimage but that uses some sort of yml recipe file

**Comment by wardwouts** [comment]
As far as I understand appimage-builder recipes depend on the software being put in the AppImage being available as .deb files. Which is why I used appimage-tool for packaging.

**Comment by WerWolv** [comment]
Ah unfortunate. I'll see if I can figure out some other way to do it then.
Anyways, thanks a lot for your contribution :)

**Comment by wardwouts** [comment]
I just realized one thing. As you already do a build in the github actions, that part of the Dockerfile can be skipped if you want to bring all this to github actions. After the build of the source code the only things being done are:

1. copying files into the correct directory structure (the `ldd` line is key for all the dependencies)
2. packing it up

(I got the information on how to do this here https://appiomatic.com/blog/creating-appimage-binary-manually-for-linux-from-your-app/ )

Copying files should be easy.  Packaging using appimage-tool may be tricky, as that uses fuse. But there is another way. Here https://github.com/AppImage/AppImageKit the README.md describes:
```
If you want to generate an AppImage manually, you can:

mksquashfs Your.AppDir Your.squashfs -root-owned -noappend
cat runtime >> Your.AppImage
cat Your.squashfs >> Your.AppImage
chmod a+x Your.AppImage
```

I'll try to get this working and wrap this up in a shellscript to get all the actual steps clear. With that it should be pretty straightforward to move everything into github actions.

**Comment by wardwouts** [comment]
Would something like this work for you?

https://github.com/wardwouts/ImHex/blob/simplify_appimage_build/dist/AppImage/package.sh

If so, I'll cleanup the no longer needed bits and create another PR.

**Comment by WerWolv** [comment]
Yeah that would be perfect, thanks a lot!

**Pull request merged**
