### PR TITLE
Store tips locally

### PR DESCRIPTION
**Pull request by iTrooz**
This PR aims to store the tips locally in ImHex (using libromfs) instead of making a net request at launch

I've noticed that even if my code is in the builtin plugin, I need to put the tips file in `resources/romfs` and not `plugins/builtin/romfs`. Is this normal ?

### CODE REVIEW

**Comment by iTrooz** [comment]
I didn't know if you wanted to keep the same behavior as the website API (a tip per day) so I did it, tell me if you want to remove it (I just have to remove the last commit)

**Comment by iTrooz** [comment]
https://github.com/WerWolv/ImHex/issues/794

**Comment by WerWolv** [comment]
> I've noticed that even if my code is in the builtin plugin, I need to put the tips file in resources/romfs and not plugins/builtin/romfs. Is this normal ?

This is definitely not right and works fine when I build it here.
There was a report of another person though (also building locally on Arch) that didn't get logos and icons displayed that I put in the built-in plugin romfs. I think some compiler flags on Arch make the linker think that the two romfs libraries are the same and it just yeets one of them

**Comment by iTrooz** [comment]
Ubuntu also wants the file to be in resources/romfs so I think this is a more a Linux vs Windows issue

Testing on Windows, it indeed wants the file to be in plugins/builtin/romfs

I will investigate more

**Comment by iTrooz** [comment]
This commit puts the tips in the builtin romfs, and check if the romfs data is valid before trying to load the tips

I think everything is working now

**Pull request merged**
