### PR TITLE
Update Chinese(Simplified) translation

### PR DESCRIPTION
**Pull request by shirok1**
Fully translated (as I can).

### CODE REVIEW

**Comment by shirok1** [comment]
I would like to translate "Regex" in string view window, however it is hard coded.

https://github.com/WerWolv/ImHex/blob/673027c82d24d3d1242530a77fe6cf3c0d9b5401/plugins/builtin/source/content/views/view_strings.cpp#L116

**Comment by WerWolv** [comment]
Hey, thanks a lot!

I'll fix the hardcoded strings in a minute

**Comment by shirok1** [comment]
Pushed.

**Comment by WerWolv** [comment]
Also it looks like you accidentally pushed an old version of the pattern language submodule to your PR. Could you remove that?

**Comment by shirok1** [comment]
Reverted.

**Comment by WerWolv** [comment]
Thank you!

**Pull request merged**
