### PR TITLE
Basic macOS support

### PR DESCRIPTION
**Pull request by filcab**
Hi all,

I've made ImHex compile on macOS and have a few commits to push if you'll accept them. All of the commits fix a single issue.
Some things are fixes to everything (making some stuff explicit instead of implicitly finding libraries). Other things are portability issues which aren't necessarily macOS-only.

My script to build is... sketchy, so I'm not pushing for any GitHub action to automatically build on macOS or anything, as I don't think we have an llvm release we can use.

Script:
```
#!/bin/sh

HOMEBREW_PREFIX="FILL YOURS IN, IT'S USUALLY /usr/local"

# assumes openssl@1.1 is installed via homebrew
export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/openssl@1.1/lib/pkgconfig":"$HOMEBREW_PREFIX/lib/pkgconfig"
export FREETYPE_DIR="$HOMEBREW_PREFIX"
# I build mine (llvm+clang+libcxx)... It requires a patch to libcxx
export LLVM_DIR=~/dev/llvm/install
export CC=$LLVM_DIR/bin/clang
export CXX=$LLVM_DIR/bin/clang++
export CXXFLAGS="-stdlib=libc++ -nostdinc++ -I$LLVM_DIR/include/c++/v1"

# last rpath is so we can link to the (system) python framework
export LDFLAGS="-L$LLVM_DIR/lib -Wl,-rpath,$LLVM_DIR/lib -Wl,-rpath,/Library/Developer/CommandLineTools/Library/Frameworks"

set -xe
cmake -H. -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release
ninja -C build
```

Then the program is available as `./build/ImHex` (not a Mac app bundle)

Patch for libcxx (needed as of yesterday):
```
diff --git a/libcxx/include/concepts b/libcxx/include/concepts
index 047e2c290f4e..b8178131f6a0 100644
--- a/libcxx/include/concepts
+++ b/libcxx/include/concepts
@@ -157,6 +157,12 @@ concept __same_as_impl = _VSTD::_IsSame<_Tp, _Up>::value;
 template<class _Tp, class _Up>
 concept same_as = __same_as_impl<_Tp, _Up> && __same_as_impl<_Up, _Tp>;
 
+// [concept.derived] (patch from https://reviews.llvm.org/D74292 )
+
+template<class _Dp, class _Bp>
+concept derived_from =
+  __is_base_of(_Bp, _Dp) && __is_convertible_to(const volatile _Dp*, const volatile _Bp*);
+
 #endif //_LIBCPP_STD_VER > 17 && defined(__cpp_concepts) && __cpp_concepts >= 201811L
 
 _LIBCPP_END_NAMESPACE_STD
```

### CODE REVIEW

**Comment by filcab** [comment]
I've force pushed with some cmake fixes: Ubuntu doesn't ship a pkgconfig definition for libmagic, so it was failing there.
Now we try a pkgconfig search, then a regular cmake library search. It's passing on the ubuntu GitHub action, finally.

**Comment by filcab** [comment]
We can now build this without toolchain patches, but still require an up to date clang+libc++ as Xcode still seems to have old stuff.

**Comment by Thog** [comment]
Just noticed your PR oops.. Currently working into getting it building and integrating it to CI so I *might* superset your PR  as a result.

> We can now build this without toolchain patches, but still require an up to date clang+libc++ as Xcode still seems to have old stuff.

I think the way to go for now will be to ensure it build under gcc 10 and LLVM 10 while redefining derived_from when missing from libcxx and building under clang

**Comment by filcab** [comment]
> I think the way to go for now will be to ensure it build under gcc 10 and LLVM 10 while redefining derived_from when missing from libcxx and building under clang

Sure. I have it based on current master, which includes the demangler extracted from LLVM, so it should build ok on gcc. I'll check out my script.

**Comment by filcab** [comment]
Here are my scripts, in case it helps with bringing up CI (both produce a working ImHex binary. I have an out of tree patch for proper rendering, which I posted on the FreeType PR):

Build with up to date clang:
```
#!/bin/sh

HOMEBREW_PREFIX="/Users/filcab/dev/brew"
export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/openssl@1.1/lib/pkgconfig":"$HOMEBREW_PREFIX/lib/pkgconfig"
export FREETYPE_DIR="$HOMEBREW_PREFIX"

# don't export, we shouldn't be using it anymore in ImHex
LLVM_DIR=~/dev/llvm/install
export CC=$LLVM_DIR/bin/clang
export CXX=$LLVM_DIR/bin/clang++
export LDFLAGS="-Wl,-rpath,/Library/Developer/CommandLineTools/Library/Frameworks"

set -xe
cmake -H. -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release
ninja -C build
```

Build with gcc-10:
```
#!/bin/sh

BUILDDIR=build-gcc

HOMEBREW_PREFIX="/Users/filcab/dev/brew"
export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/openssl@1.1/lib/pkgconfig":"$HOMEBREW_PREFIX/lib/pkgconfig"
export FREETYPE_DIR="$HOMEBREW_PREFIX"

export CC=$HOMEBREW_PREFIX/bin/gcc-10
export CXX=$HOMEBREW_PREFIX/bin/g++-10
export LDFLAGS="-Wl,-rpath,/Library/Developer/CommandLineTools/Library/Frameworks"

set -xe
cmake -H. -B$BUILDDIR -GNinja -DCMAKE_BUILD_TYPE=Release
ninja -C $BUILDDIR
```

**Comment by filcab** [comment]
Updated with the latest (Thanks a lot, my cmake commit is now just a few lines!).
Scripts work and produce a proper binary.

**Comment by Thog** [comment]
I got something to build and that work on Apple Silicon! 🎉 
Still need to reimplement std::bit_set if it's missing (only commented the call out for now).
I also took the liberty to not use system python install as this bring more issues than anything

See https://github.com/Thog/ImHex/tree/feature/macos-support

**Comment by filcab** [comment]
> I got something to build and that work on Apple Silicon! 🎉
Yay!

> Still need to reimplement std::bit_set if it's missing (only commented the call out for now).
Hmm, I didn't notice that issue, but that's because I'm using up to date compilers, probably. I guess Xcode's doesn't support it yet.

> I also took the liberty to not use system python install as this bring more issues than anything
Yup. We'd need to do that eventually if we're to create a `.app` for ImHex anyway.

> See https://github.com/Thog/ImHex/tree/feature/macos-support
Thanks, will take a look!

**Comment by filcab** [comment]
btw, in a pinch, cppreference has a possible definition:
https://en.cppreference.com/w/cpp/numeric/bit_ceil

**Comment by Thog** [comment]
> btw, in a pinch, cppreference has a possible definition:
> https://en.cppreference.com/w/cpp/numeric/bit_ceil

Everything ready to add on master I think, going to merge it after github actions complete its job (still waiting for it to start)

**Comment by Thog** [comment]
Closing as of https://github.com/WerWolv/ImHex/commit/310059f2740ccc85333dc77380993631a5d91b49

**Comment by filcab** [comment]
Cool, works on my machine!
Thanks!

**Pull request closed without merging**
