### PR TITLE
add MacOS arm64 job

### PR DESCRIPTION
**Pull request by iTrooz**
I said I'll do it in #1414

Warning: the output zip does not pass SIP (System Integrity Protection), and I have no plan to do it for now. So if someone here has a Mac, feel free to to try to fix the problem (which is probably our build system)

Link #1109

### CODE REVIEW

**Comment by iTrooz** [comment]
Note: this PR adds a dependency on a binary artifact in my repository https://github.com/iTrooz/macos-crosscompile (the docker image package)

**Comment by iTrooz** [comment]
Also, note that the job in this PR is dependent on a package in one of my repository: ghcr.io/itrooz/macos-crosscompile:clang17-nosdk

**Comment by WerWolv** [comment]
Is ghcr.io/itrooz/macos-crosscompile:clang17-nosdk mainly meant for compiling ImHex now? I wouldn't mind having it on my / this repos docker repository if you don't want to have it depend on your repo. I'm fine with how it is now too though

**Comment by iTrooz** [comment]
> Is ghcr.io/itrooz/macos-crosscompile:clang17-nosdk mainly meant for compiling ImHex now

Right now yeah, but I tried to make it generic, and added a README so that other people can use it. And I plan to *relatively* maintain it for general use

I think it's better if it stays in my repository, so we don't maintain two versions of the same thing

I still kept an (unused) copy of the Dockerfile is this repository (that I don't plan to update), just in case

**Pull request merged**
