### PR TITLE
Fix usage of CMAKE_INSTALL_PREFIX on Linux

### PR DESCRIPTION
**Pull request by manokara**
Typically one would install locally built packages in the `/usr/local` prefix, which is the default value of `CMAKE_INSTALL_PREFIX`, by running `make install`. However, the way the variable is used in the CMake definitions assumes that `CMAKE_INSTALL_PREFIX` is `/`, which would generate incorrect paths (e.g. `/usr/local/usr/bin/imhex` instead of `/usr/local/bin/imhex`). This PR aims to fix that.

### CODE REVIEW

**Comment by WerWolv** [comment]
Thanks! This does mess up packaging of all Linux artifacts though. Can you adjust the github actions build script too so it puts the files in the /usr folder there (or fix the paths to point to the non-usr directory, not sure which one is better)

**Comment by manokara** [comment]
Oh indeed, `CMAKE_INSTALL_PREFIX` is overriden for packaging. In that case I should probably add `/usr` directly in the build script so it still respects the prefix in local builds.

**Comment by WerWolv** [comment]
Cool thanks! The DEBIAN folder still gets added to e.g the ELF artifact though. You'd have to copy it over in the workflow script, then package the deb package and then delete the file again because the other upload/package steps act on the same `build/install` folder as the DEB one

**Comment by manokara** [comment]
Should I squash the commits?

**Comment by WerWolv** [comment]
I'll squash them when I merge the PR. Just waiting for the CI to run now before I merge. Thanks a lot :)

**Pull request merged**
