### PR TITLE
m1 build

### PR DESCRIPTION
**Pull request by krocki**
builds using provided instructions on Apple M1 macbook pro

### CODE REVIEW

**Comment by WerWolv** [comment]
Hi! The unused ranges include is already gone now. However the four other lines are really required for is_integral to properly pick up s128 and u128. You can't just remove them.
If you're still interested in this PR, please fix building by moving these lines to an appropriate place instead of removing them. 

I don't have a mac so the only real way for me to test compilation there is with the GitHub Actions which right now takes up to 3 hours sometimes to start...

**Comment by WerWolv** [comment]
More information about this, it builds absolutely fine with clang 11.0.0 on Arch Linux. I'm really not sure why it should be failing on Mac

**Comment by WerWolv** [comment]
The issue seems to have been that libc++ already defines is_integral and is_signed for 128 bit types. Only including them when not using it fixed the issue.

**Comment by krocki** [comment]
thanks, I'm going to give it another try

**Pull request closed without merging**
