### PR TITLE
fix errors when compiling example_cpp

### PR DESCRIPTION
**Pull request by dianwoshishi**

### CODE REVIEW

**Comment by WerWolv** [comment]
Thank you!

**Comment by WerWolv** [comment]
Btw, there's this repo here that can be used as a template too: https://github.com/WerWolv/ImHex-Cpp-Plugin-Template
Need to update it to 1.14.0 but it would allow for a much cleaner build process for your plugin

**Comment by WerWolv** [comment]
Updated it

**Comment by dianwoshishi** [comment]
OK！
why not convert it to a submodule in /plugin/example_cpp？

**Comment by WerWolv** [comment]
Because the point of that template is that you can build Plugins out-of-tree without having to maintain a fork of ImHex itself.

**Comment by dianwoshishi** [comment]
> Because the point of that template is that you can build Plugins out-of-tree without having to maintain a fork of ImHex itself.

got it!

**Pull request merged**
