### PR TITLE
build: move third party libraries to lib/third_party

### PR DESCRIPTION
**Pull request by iTrooz**

### CODE REVIEW

**Comment by WerWolv** [comment]
Should we maybe keep imgui in the external folder? Since there's a bunch of custom stuff in there

**Comment by iTrooz** [comment]
We do, but isn't most of this stuff from different third party repositories ? (e.g. imgui, implot, imnodes, imstb..) Is there anything in there except CMakeLists.txt that we have created ?

**Comment by WerWolv** [comment]
The fonts are custom, the glfw backend has a bunch of changes, the TextEditor has a ton of changes and the imgui config is in there

**Comment by iTrooz** [comment]
To me it still seems like most of the code is third party, and we just made changes to it, but if you really want to move it to lib/external, I don't have anything against it

**Comment by WerWolv** [comment]
Hm. No I think it's okay. Let's leave it the way you do it

**Pull request merged**
